kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubeapp-production-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dizertatie-db
      version: "1"
  template:
    metadata:
      name: kubeapp-db
      labels:
        app: dizertatie-db
        version: "1"

    spec:
      containers:
        - name: kubeapp-db
          image: mysql:5.7
          imagePullPolicy: Always
          ports:
            - name: kubeapp-db
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: 'webapplication'
            - name: MYSQL_ROOT_PASSWORD
              value: 'mypassword'
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /etc/mysql/conf.d/mycustom.cnf
              name: mysql-config
      volumes:
        - name: mysql-data
          hostPath:
            path: "/Users/eusebiu.rizescu/dizertatie/mysql"
        - name: mysql-config
          hostPath:
            path: "/Users/eusebiu.rizescu/dizertatie/mysql-conf/mycustom.cnf"