kind: Service
apiVersion: v1
metadata:
  name: dizertatie-service-db
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: dizertatie-db
    version: "1"