stages:
  - canary

image:
  name: traherom/kustomize-docker
  entrypoint: [""]

deploy_canary:
  tags:
    - docker
  stage: canary
  before_script:
    - kubectl version
  script:
    - cd Deployment-Canary
    - for i in *; do sed -i "s|CI_PROJECT_PATH_SLUG|${CI_PROJECT_PATH_SLUG}|g" "$i"; done
    - for i in *; do sed -i "s|CI_ENVIRONMENT_SLUG|${CI_ENVIRONMENT_SLUG}|g" "$i"; done
    - kubectl apply -f deployment-version1.yml -f service-version1.yml -f ingress-version1.yml -f deployment-version2.yml -f service-version2.yml -f ingress-version2.yml
  environment:
    name: staging
    url: https://staging.example.com
  #when: manual
