version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /docker/prometheus/prometheus_db:/var/lib/prometheus
      - /docker/prometheus/prometheus_db:/prometheus
      - /docker/prometheus/prometheus_db:/etc/prometheus
      - /docker/prometheus/alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=2000h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /docker/grafana/grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - monitor-net

networks:
  monitor-net:
    internal: false
