{
 "title": "Dizertatie Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(requests200V1 + requests500V1) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "Traffic Version 1"
    },
    {
     "expr": "(requests200V2 + requests500V2) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "Traffic Version 2"
    },
    {
     "expr": "(requests500V1 + requests500V2) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "Error Rate Total"
    },
    {
     "expr": "(requests500V2) / (requests200V2 + requests500V2 + 0.1) * 100",
     "legendFormat": "Error Rate Version 2"
    }
   ]
  },
  {
   "title": "Traffic distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(requests200V1 + requests500V1) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "Traffic V1"
    },
    {
     "expr": "(requests200V2 + requests500V2) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "Traffic V2"
    }
   ]
  },
  {
   "title": "Response Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(requests500V1 + requests500V2) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "Error rate Total"
    },
    {
     "expr": "(requests200V1 + requests200V2) / (requests200V1 + requests200V2 + requests500V1 + requests500V2) * 100",
     "legendFormat": "OK rate Total"
    }
   ]
  },
  {
   "title": "200 OK",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests200V1 + requests200V2", "legendFormat": "200 Total" },
    { "expr": "requests200V1", "legendFormat": "200 V1" },
    { "expr": "requests200V2", "legendFormat": "200 V2" }
   ]
  },
  {
   "title": "500 ERROR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests500V1 + requests500V2", "legendFormat": "500 Total" },
    { "expr": "requests500V1", "legendFormat": "500 V1" },
    { "expr": "requests500V2", "legendFormat": "500 V2" }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "requests200V1 + requests200V2", "legendFormat": "200 Total" },
    { "expr": "requests500V1 + requests500V2", "legendFormat": "500 Total" },
    {
     "expr": "requests200V1 + requests200V2 + requests500V1 + requests500V2",
     "legendFormat": "Total traffic"
    }
   ]
  }
 ]
}